### ISSUE TITLE
инсталяция

### ISSUE THREAD

**Issue by Ulibka68** [fsa/phpmd#2]
Добрый день, подскажите пожалуйста про инсталяцию приложения.
Для начала я попробовал запустить приложение на openserver, начальную директорию настроил на htdocs - но не заработало.

Посмотрел таски в gulpfile.js - но какого то общего таска сборки не нашел, посмотрел на директорию htdocs - показалось что все необходимые действия выполнены.

Перед запуском запустил npm install

Понятно что на openserver демоны работать не будут, но просто захотелось посмотреть запустится/нет.

**Comment by fsa** [comment]
В приложении используется разделяемая память. На Windows она не работает,
на сколько я знаю. Нужен Linux или bsd сервер.

пт, 30 нояб. 2018 г., 14:33 Gayrat Vlasov notifications@github.com:

**Comment by fsa** [comment]
Проект изначально не предполагал запуск на Windows ввиду отсутствия поддержки используемых возможностей PHP.
